import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontNeueMontreal = {
  className: "font-neue-montreal",
  style: {
    fontFamily: "'Neue Montreal', sans-serif",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload font utama */}
        <link
          href="https://fonts.googleapis.com/css2?family=Neue+Montreal:wght@400;500;700;900&display=swap"
          rel="stylesheet"
        />
        
        {/* Favicon (uncomment jika sudah ada) */}
        {/* <link rel="icon" href="/favicon.ico" /> */}

        {/* Tailwind CSS (direkomendasikan menggunakan npm package, bukan CDN) */}
        {/* Hapus CDN jika sudah menginstall Tailwind via npm */}
        {/* <link
          href="https://cdn.jsdelivr.net/npm/tailwindcss@latest/dist/tailwind.min.css"
          rel="stylesheet"
        /> */}

        {/* jQuery dan DataTables */}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js" async />
        <link
          rel="stylesheet"
          href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css"
        />
        <Script
          src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"
          strategy="beforeInteractive"
        />

        {/* TwElements */}
        <link
          href="https://cdn.jsdelivr.net/npm/tw-elements@latest/dist/css/tw-elements.min.css"
          rel="stylesheet"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/tw-elements@latest/dist/js/tw-elements.umd.min.js"
          strategy="afterInteractive"
        />

        {/* SweetAlert2 */}
        <Script
          strategy="afterInteractive"
          src="https://cdn.jsdelivr.net/npm/sweetalert2@11"
        />
      </head>
      
      <body 
        className={fontNeueMontreal.className}
        style={fontNeueMontreal.style}
      >
        {children}
      </body>
    </html>
  );
}